version: '3.8'
services:
  app:
    build: .
    container_name: progavanzada-app
    ports:
      - "8090:8090"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/playlistdb

  mongo:
    image: mongo:7.0
    container_name: progavanzada-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
